apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: user-4
spec:
  containers:
  - image: busybox
    name: busybox
    env:
    - name: DUMMY_DATABASE_PASSWORD
      value: "admin"
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(DUMMY_DATABASE_PASSWORD) > /html/index.html; sleep 10; done"]
    volumeMounts:
    - mountPath: /html
      name: log-volume
  - image: nginx
    name: nginx
    env:
    - name: DUMMY_DATABASE_PASSWORD
      value: "admin"
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
    startupProbe:
      httpGet:
        port: 80
        path: /
      initialDelaySeconds: 3
      periodSeconds: 3
      timeoutSeconds: 1
    livenessProbe:
      httpGet:
        port: 80
        path: /
      failureThreshold: 3
      periodSeconds: 5
    readinessProbe:
      tcpSocket:
        port: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: log-volume
  volumes:
    - name: log-volume
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: ClusterIP